### PR TITLE
added logo and favicon

### PR DESCRIPTION
**Pull request by codewithnadeem14502**
Screenshot (289)
hope you like it sir .

### CODE REVIEW

**Comment by codewithnadeem14502** [comment]
Screenshot (291)
sir what happen ???

**Review by tob — CHANGES_REQUESTED** [review]
HI, I'm happy with the design but please use a squared icon to avoid it to be stretched. If you take a look at your screenshot you can see that the image is squeezed. If you want to learn more about favicon, the importance of sizes and how to create them please check this article. 

https://www.creativebloq.com/illustrator/create-perfect-favicon-12112760#section-favicon-design-rules

**Comment by tob** [comment]
> Screenshot (291) sir what happen ???

I think this is the automatic status that you get when opening a PR.

**Comment by codewithnadeem14502** [comment]
sir add the favicon / logo as per your requirement , please check you like my work 
Screenshot (296)
Screenshot (297)
 ,

**Comment by codewithnadeem14502** [comment]
> HI, I'm happy with the design but please use a squared icon to avoid it to be stretched. If you take a look at your screenshot you can see that the image is squeezed. If you want to learn more about favicon, the importance of sizes and how to create them please check this article.
> 
> https://www.creativebloq.com/illustrator/create-perfect-favicon-12112760#section-favicon-design-rules

sir , in my screen shot the log squeezed because i crop that screenshot , now i have fix all the issue please check it sir

**Comment by codewithnadeem14502** [comment]
Screenshot (297)
Screenshot (299)
Succesfully added the logo/favicon , squeezed issue it also fix, and i use square icons only . 
hope you like my work

**Pull request merged**
